### ISSUE TITLE
Can't access LLink in LGraphNode.js?

### ISSUE THREAD

**Issue by liusida** [litegraph-tsx/litegraph.tsx#15]
```
    // create link class
    link_info = new LLink(
      nextId,
      input.type || output.type,
      this.id,
      slot,
      target_node.id,
      target_slot,
    );
```

Uncaught ReferenceError: LLink is not defined
    at NodeStart.connect (LGraphNode.js:2003:5)
    at LGraphCanvas.processMouseUp (LGraphCanvas.js:1550:36)

I think I should stay with the old project for a little longger... xD

**Comment by daniel-lewis-ab** [comment]
Thanks.  I'll look into this one.

Main just did the es6 migration this weekend and is still behind my
personal repo a little, but its quickly catching up and has incorporated
some lessons learned.

**Comment by daniel-lewis-ab** [comment]
https://github.com/litegraph-tsx/litegraph.tsx/commit/9197ab9ed8d18892e7abb16c59b6167164473d50
